### ISSUE TITLE
request for credentials.txt

### ISSUE THREAD

**Issue by vishytheking** [xmd79/trading-bot-using-time-series#1]
when i tried to run the first file i get the following error
PS C:\Users\Lenovo\Downloads\trading-bot-using-time-series-main> & "C:/Program Files/Python312/python.exe" c:/Users/Lenovo/Downloads/trading-bot-using-time-series-main/arb1.py
Traceback (most recent call last):
  File "c:\Users\Lenovo\Downloads\trading-bot-using-time-series-main\arb1.py", line 5, in <module>
    with open("credentials.txt", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.txt'

**Comment by vishytheking** [comment]
i solved the probelm by creating a empty file  credentials.txt in the same folder.. its working.. thanks

**Comment by xmd79** [comment]
> i solved the probelm by creating a empty file credentials.txt in the same folder.. its working.. thanks

lol, yea, sorry for lack of comments on code about some details, forgot to add those about the credentials.txt file, yea , u need that txt file in same folder with the py bot code, btw, made another bot for scalp called scalper34, see if u like it, it's a cool idea for some fast cycles scalper for spot. cheers )
